### ISSUE TITLE
error: linking with `flip-link` failed: exit status: 1

### ISSUE THREAD

**Issue by MilicaStoj** [bedroombuilds/pico-usb#1]
Hi Michael,

I tried compiling the rp2040-blink project, with everything from the list of dependencies installed:

```
# install compilation targets
rustup target add thumbv6m-none-eabi
rustup target add --toolchain nightly thumbv6m-none-eabi
# necessary linker
cargo install flip-link
# Useful to creating UF2 images for the RP2040 USB Bootloader
cargo install elf2uf2-rs --locked
# Useful for flashing over the SWD pins using a supported JTAG probe
cargo install probe-run
# most comfortable way of running and looking at logs
cargo install cargo-embed

```

**But I get an error : error: linking with `flip-link` failed: exit status: 1, when running cargo +nightly build. I am using cargo 1.77.0 (3fe68eabf 2024-02-29) and rustc 1.77.0 (aedd173a2 2024-03-17).**

Detailed error:
ubuntu@ubuntu-virtual-machine:~/Documents/rustfest_workshop/pico-usb/rp2040-blink$ cargo +nightly build
   Compiling compiler_builtins v0.1.109
   Compiling core v0.0.0 (/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling proc-macro2 v1.0.85
   Compiling unicode-ident v1.0.12
   Compiling syn v1.0.109
   Compiling semver-parser v0.7.0
   Compiling cortex-m v0.7.7
   Compiling version_check v0.9.4
   Compiling cortex-m-rt v0.7.3
   Compiling semver v0.9.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling defmt v0.3.8
   Compiling thiserror v1.0.61
   Compiling proc-macro-error v1.0.4
   Compiling debug-helper v0.3.13
   Compiling rustc_version v0.2.3
   Compiling paste v1.0.15
   Compiling defmt-macros v0.3.9
   Compiling crc-any v2.5.0
   Compiling bare-metal v0.2.5
   Compiling rp2040-pac v0.4.0
   Compiling panic-probe v0.3.2
   Compiling rp-pico v0.7.0
   Compiling quote v1.0.36
   Compiling defmt-rtt v0.4.1
   Compiling rp2040-blink v0.1.0 (/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink)
   Compiling rp2040-boot2 v0.2.1
   Compiling syn v2.0.66
   Compiling cortex-m-rt-macros v0.7.0
   Compiling num_enum_derive v0.5.11
   Compiling thiserror-impl v1.0.61
   Compiling rp2040-hal-macros v0.1.0
   Compiling defmt-parser v0.3.4
   Compiling rustc-std-workspace-core v1.99.0 (/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling nb v1.1.0
   Compiling vcell v0.1.3
   Compiling void v1.0.2
   Compiling bitfield v0.13.2
   Compiling nb v0.1.3
   Compiling volatile-register v0.2.2
   Compiling arrayvec v0.7.4
   Compiling embedded-hal v0.2.7
   Compiling num_enum v0.5.11
   Compiling critical-section v1.1.2
   Compiling either v1.12.0
   Compiling bitflags v1.3.2
   Compiling gcd v2.3.0
   Compiling stable_deref_trait v1.2.0
   Compiling itertools v0.10.5
   Compiling fugit v0.3.7
   Compiling embedded-dma v0.2.0
   Compiling pio v0.2.1
   Compiling rand_core v0.6.4
   Compiling usb-device v0.2.9
   Compiling rp2040-hal v0.8.2
error: linking with `flip-link` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/ubuntu/.local/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" VSLANG="1033" "flip-link" "-flavor" "gnu" "/tmp/rustc4k5HbS/symbols.o" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/rp2040_blink-7f19b1136b3a22a7.rp2040_blink.e6064bbffc83260-cgu.0.rcgu.o" "--as-needed" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/debug/deps" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/build/rp2040-blink-fcfc5897f6a3eedc/out" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/build/cortex-m-2207370ae03c468b/out" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/build/cortex-m-rt-8645a0c69b81e172/out" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/build/defmt-0232f97dcec6d557/out" "-L" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/build/rp2040-pac-9ae2c0ece3bdaf3f/out" "-L" "/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-Bstatic" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp_pico-de5d370718b608bc.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_boot2-705700f3c7c5ee09.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libitertools-ba81ddecb600b86d.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libeither-b5ca615d46b0699d.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librand_core-158ffc40f326f043.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libusb_device-8d119eab976bb7aa.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libpio-09ca6f2be3ce0595.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libnum_enum-c126925f0be6deec.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libarrayvec-8dc5c9c837ed85bb.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libembedded_dma-8d2fed56808aa9c6.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libstable_deref_trait-87c576ed630f781a.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libfugit-5d5cbdac3d92b3b2.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libgcd-83017df81f057ff1.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_pac-94e4c346b9c15e2b.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcortex_m_rt-600dfd4ecca1d8f5.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libpanic_probe-3899322552602ada.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcortex_m-453dc17f3d773ed9.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libvolatile_register-8eadb22964b3bb85.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libvcell-49fc0e7b3a47372b.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libbare_metal-a13963be36a95160.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libembedded_hal-e2b28070ded7d8cf.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libvoid-1037abb192405477.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libnb-68c462e6e00ac3f7.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libnb-0f5e751682b9d572.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libdefmt_rtt-1b1e3cfe89a1b214.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcritical_section-794dc8badf807bad.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libdefmt-f1a20fbfabcb4e2a.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libbitflags-8d6e3669f78c8a3c.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librustc_std_workspace_core-6ec600c17aaf3d02.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcore-ea8636d6431cf0f6.rlib" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib" "-Bdynamic" "--eh-frame-hdr" "-z" "noexecstack" "-L" "/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-o" "/home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/rp2040_blink-7f19b1136b3a22a7" "--gc-sections" "-O1" "--nmagic" "-Tlink.x" "-Tdefmt.x"
  = note: rust-lld: error: duplicate symbol: __clzsi2
          >>> defined at intrinsics.rs:18 (src/intrinsics.rs:18)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__clzdi2) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at leading_zeros.rs:32 (src/int/leading_zeros.rs:32)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__clzsi2+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __addsf3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__addsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__addsf3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __addsf3vfp
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__addsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__addsf3vfp+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __floatdisf
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__floatdisf) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__floatdisf+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __fixsfsi
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__fixsfsi) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__fixsfsi+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __divsf3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__divsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__divsf3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __divsf3vfp
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__divsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__divsf3vfp+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __mulsf3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__mulsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__mulsf3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __mulsf3vfp
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__mulsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__mulsf3vfp+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __subsf3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__subsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__subsf3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __subsf3vfp
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__subsf3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__subsf3vfp+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __divmodsi4
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__divmodsi4) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__divmodsi4+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __divsi3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__divsi3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__divsi3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __modsi3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__modsi3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__modsi3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __udivsi3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__udivsi3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:364 (src/macros.rs:364)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__udivsi3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __umodsi3
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__umodsi3) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__umodsi3+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          rust-lld: error: duplicate symbol: __udivmodsi4
          >>> defined at intrinsics.rs:225 (src/intrinsics.rs:225)
          >>>            rp2040_hal-e3e4c362178453c8.rp2040_hal.b9c334310dda472a-cgu.0.rcgu.o:(__udivmodsi4) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/librp2040_hal-e3e4c362178453c8.rlib
          >>> defined at macros.rs:499 (src/macros.rs:499)
          >>>            compiler_builtins-bd13b3db424d6255.compiler_builtins.abace79300e38120-cgu.0.rcgu.o:(.text.__udivmodsi4+0x1) in archive /home/ubuntu/Documents/rustfest_workshop/pico-usb/rp2040-blink/target/thumbv6m-none-eabi/debug/deps/libcompiler_builtins-bd13b3db424d6255.rlib
          
          flip-link: the native linker failed to link the program normally; please check your project configuration and linker scripts

**Comment by mike-kfed** [comment]
That was due to a broken `.cargo/config.toml` file where then intrinsics of ARM cpus are doubly defined. Should be fixed with my recent commit.

Side note: nightly is no longer needed to build here, stable rustc is fine :)

**Comment by MilicaStoj** [comment]
Looks good, thanks :)
